name: weather_tulu_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  retrofit: ^4.4.1
  weather_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
